In [13]:
import cv2
from PIL import Image
import numpy as np

In [15]:
model = cv2.ml.ANN_MLP_load('IOT_Project/mlp_xml/mlp_1522002066.xml')

In [24]:
img = cv2.imread('IOT_Project/training_images_raw/fwd_left/frame01331.jpg', 0)
print(img.shape)
print(img)
# cv2.imshow('image', img)
# cv2.waitKey(1)
# cv2.destroyAllWindows()

(120, 320)
[[111 112 113 ... 113 113 100]
 [111 112 113 ... 115 115 103]
 [112 112 113 ... 115 116 104]
 ...
 [106 107 107 ... 122 121 107]
 [106 108 108 ... 121 120 108]
 [106 108 109 ... 119 119 109]]


In [25]:
test_img = img.reshape((1, 38400)).astype(np.float32)

In [26]:
print(test_img)

[[111. 112. 113. ... 119. 119. 109.]]


In [27]:
ret, resp = model.predict(test_img)

In [28]:
print resp.argmax(-1)

[0]
